server:
  port: 0



---
spring:
  profiles: docker

server:
  port: 8090

app:
  rabbitmq:
    host: rabbitmq

eureka:
  numberRegistrySyncRetries: 0
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaService:8761/eureka/