server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    ROOT: INFO
---
spring:
  profiles: docker

server:
  port: 8761

eureka:
  numberRegistrySyncRetries: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    ROOT: INFO


